### ISSUE TITLE
Mac Only?

### ISSUE THREAD

**Issue by insign** [LKDevelopment/forge-connect#5] opened 2017-01-09 14:49 UTC
What is the problem to work on Linux/Ubuntu?

**Comment by LKaemmerling** [comment] 2017-01-09 15:56
At the moment it is Mac Only because of this line 
https://github.com/LKDevelopment/forge-connect/blob/master/src/ConnectToServerCommand.php#L44

i planed a complete overhaul when the new official forge api is released.  But of course, you are free to contribute a fix for this too :)

**Comment by LKaemmerling** [comment] 2017-01-09 17:51
@insign i implement something that should be helpful for you. Just update forge-connect from dev-master and add in your home path in the .forgeConnect/config.json the following line:

"console":"ssh {user}@{ip_address}" and save this. {user} and {ip_address} are placeholders that are replaced by forge-connect. You can provide the command in this file. Can you test this? I have no Ubuntu Desktop.

**Comment by insign** [comment] 2017-01-09 17:58
Ok, gimme some minutes...

**Comment by insign** [comment] 2017-01-09 18:19
[image: Imagem inline 1]

*Hélio Araújo de Oliveira*
Evite correntes de e-mails e combata o spam.
Prefira materiais reciclados, incluindo papel

2017-01-09 14:51 GMT-03:00 Lukas Kämmerling <notifications@github.com>:

**Comment by insign** [comment] 2017-01-09 18:19
![image](https://cloud.githubusercontent.com/assets/1113045/21777767/0ae118cc-d67f-11e6-9633-cf79aaaf6273.png)

**Comment by LKaemmerling** [comment] 2017-01-09 19:59
have you entered the correct passphrase? Try to reregister your credentials.

**Comment by insign** [comment] 2017-01-09 20:03
Now worked. The problem was in the register, that at first time, gave an error with mkdir.

**Comment by insign** [comment] 2017-01-09 20:05
server list worked fine, not connect

![image](https://cloud.githubusercontent.com/assets/1113045/21781343/b73cc4fa-d68d-11e6-848b-43487f1bfcd6.png)


Laravel Envoy cannot help with it?

**Comment by LKaemmerling** [comment] 2017-01-09 20:09
Envoy is on the Server, Forge Connect is on your client (normally your computer). The Problem is, that i haven't an idea how i start a new terminal from terminal (with Symfony Process). On the mac it is simply "open ssh://user@ip".

**Comment by insign** [comment] 2017-01-09 20:11
This projects not help?

https://github.com/search?l=PHP&q=ssh&type=Repositories&utf8=%E2%9C%93

**Comment by LKaemmerling** [comment] 2017-01-09 20:34
I've tried something, but actually it doesn't work because i can't start a new ssh process from php that is accessible in the parent terminal app. I think it is only some playing with the command, but i have no idea what i should do to make it working on ubuntu.

**Comment by LKaemmerling** [comment] 2017-01-09 20:43
@insign i think i have it :) can you update from master and add in your ~/.forgeConnect/config.json under "console" the command: "ssh {user}@{ip_address}" and try to connect again?

**Comment by insign** [comment] 2017-01-10 18:01
I did not found anything but:

`{
    "credentials": {
        "email": "insign@gmail.com",
        "password": "key here"
    }
}
`

But, the right command is `ssh ip -l user`

**Comment by LKaemmerling** [comment] 2017-01-10 18:19
```{ "credentials": { "email": "insign@gmail.com", "password": "key here" },"console": "ssh {ip_address}  -l {user}"  }```

Copy Paste this and replace your password key. Than it should work :)

**Comment by insign** [comment] 2017-01-10 18:59
It worked fine, but I'm working in somethign better...

**Comment by insign** [comment] 2017-01-10 20:26
Please check #7

**Comment by LKaemmerling** [comment] 2017-01-10 20:47
1.2.0 is released, so enjoy it :) Thank you for your work on this!

**Closed as completed by LKaemmerling** 2017-01-10 20:47 UTC
Labels: enhancement, 1.2.0
